services:
  cards-against-humanity:
    build:
      context: .
      args:
        - GIT_TAG=${GIT_TAG:-dev}
    image: ascii-arcade/cards-against-humanity:${GIT_TAG:-dev}
    ports:
      - ${SSH_PORT:-23234}:${ASCII_ARCADE_SSH_PORT:-23234}
    restart: always
    env_file:
      - .env
    environment:
      - ASCII_ARCADE_LANG="EN"
    volumes:
      - ssh:/app/.ssh

volumes:
  ssh:
